### ISSUE TITLE
[IMPORTANT] Script path issues

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI_522_Group313#49]
- For all scripts, default file_dir should be data/ or eda/, not ../data
- The usage instructions tell you to set directory to src/ but if you do that you can't find the data folder. Instead run eg src/load_data.R

The Usage instructions are very thorough, and linking from the README works well given their length - but you need to make sure that if the user follows the usage instructions the scripts will run!

**Comment by agdal1125** [comment]
@ksedivyhaley thank you for the feedback. I noticed that Github doesn't upload empty folder... I should have added README.md to prevent this from happening.  
I have a question. If the default file_dir should be data/  does this mean the data folder should be a child directory of the src folder?

**Comment by ksedivyhaley** [comment]
My recommendation is to leave the data folder in the main project folder (not as a child of src) **and also** to run scripts as src/script_name. If you do this, when your script looks for the directory `data/` it will be looking for something in the main project folder and will find the correct folder (assuming it exists).

**Comment by agdal1125** [comment]
Thank you for the advice. I will make the changes accordingly
