### ISSUE TITLE
Report feedback - good, minor improvements

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI_522_Group313#53]
Well done on:

- Good high-level overview in README
- Excellent introduction of research question and data set
- Good description of your figure & interpretation of results in context of question

Improvements:

- Critique limitations of your analysis
- Use polished axis labels for your figures
- Additional figure(s) would be helpful, particularly:
  - is there a metric for feature importance you could graph to compare the relative importance of your top 5 features, and perhaps the next several features? (impurity decrease?)
  - "linear regression was not an option since our exploratory data analysis revealed an unclear linear relationship with our response variable price." - show this in your report
- Proofread, eg: "Table 1: This graph"

**Comment by suvarna-m** [comment]
Thanks Kate! In our updated final report, I added some critiques/limitations of our analyses, added more figures (e.g. showing the lack of linear relationships from the EDA), updated our existing images with better axis/title labels, and fixed typos like the one listed above.
