### ISSUE TITLE
Peer Feedback

### ISSUE THREAD

**Issue by agdal1125** [UBC-MDS/DSCI_522_Group313#57]
- Some of the features are irrelevant to the objective of the research question.
- Encourage implementing feature selection for the accuracy of the model
- Training & Testing time should be discussed in the final report

**Comment by suvarna-m** [comment]
- included runtimes in the final report
- added more most-important features (total of 10, was 5 before) in the final report to help resolve the issue of irrelevant features
- mentioned dropping the irrelevant columns and implementing feature selection as limitations/next steps for the next iteration
