### ISSUE TITLE
Milestone 3: mechanics feedback

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI_522_Group313#67]
- **List selenium as dependency**
- More conversaton in issues (don't just post them, discuss)
- At this point, your eda can be moved into the src or docs directory.
- Glad to see you're keeping the usage instructions in the src folder up to date even though your main README cites Make!

**Comment by agdal1125** [comment]
@ksedivyhaley  Hello Kate! `At this point, your eda can be moved into the src or docs directory.` Are you suggesting relocation of the entire eda folder to src or docs?

**Comment by ksedivyhaley** [comment]
Actually, taking a second look at that I wouldn't bother. Many groups have incorporated their eda files into other folders (either as a sub-folder or just including the eda report in `docs` and the csv/image files in `results`) but your setup is perfectly reasonable as well.

**Comment by agdal1125** [comment]
@suvarna-m once you add the selenium dependency you can close this issue

**Comment by suvarna-m** [comment]
Thanks Kate! Selenium has been added as a dependency ( #78 ). We will keep eda folder as-is based on your feedback in this thread. Also, as discussed in lab yesterday, most of our group conversations have been in-person (hence the lack of GitHub conversations) - we will attempt to move more of our conversations to GitHub for this milestone.
