### ISSUE TITLE
Milestone 3: Code Quality

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI_522_Group313#68]
- Makefile should have a brief summary at the top that answers who wrote it, when it was written and what it does.
- check_files includes good tests - please call this function at the start of main() to make sure it runs!
- In processing script, would still like to see better documentation of how you derive the directory for the split data from the store_path - an extra code comment on the line it happens stating what you're doing, and a sentence in the main script summary saying where the split data directory is, would be enough.

**Comment by agdal1125** [comment]
@camadi I will work on the documentation
