### ISSUE TITLE
Milestone 3: Viz feedback

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI_522_Group313#71]
- Good improvements on Fig 2
- Choice of what data to show in your two new figures is good, but figures themselves need improvement to be informative.
- Figure 1 is really tiny. Make these bigger and display on 2 rows of graphs.
  - You can get rid of the price vs price graph for 4 graphs per row
  - The axis labels for this may need to be improved as you did for Figure 2 (I can't read the Fig 1 labels so can't tell if they'd be reader-friendly at a larger size!)
- Figure 3 should be an actual figure, not a screenshot!

**Comment by agdal1125** [comment]
- Figure 1 - Replaced the old plot with a heatmap 
- Figure 3 - Resolved with creating a feature importance plot
