### ISSUE TITLE
Visualizations feedback

### ISSUE THREAD

**Issue by firasm** [UBC-MDS/DSCI_522_Group313#72]
Hey folks, sorry I wasn't able to give you feedback on your visualizations before lab today (I ran out of time), can you please flag me down today in the queue (just add your group number so I can get to you earlier) and I can give you some feedback in person? Sorry!

**Comment by suvarna-m** [comment]
Hi Team @agdal1125 @camadi ,
Here is the in-person visualization feedback from Firas:
- Figure 1: Try to make it more of a heatmap/correlation plot; this will fix the issue of it being too small
- Figure 2: Order the models from largest to smallest
- Figure 3: Combine the most important features and their scores into a table/plot

**Comment by agdal1125** [comment]
- Figure 1 completed.

**Comment by agdal1125** [comment]
- Figure 2 & 3 completed.
