### ISSUE TITLE
Makefilegraph

### ISSUE THREAD

**Issue by agdal1125** [UBC-MDS/DSCI_522_Group313#84]
Does our makefilegraph plot need to include every images and files that our script generates?

**Comment by ksedivyhaley** [comment]
It should be the image that makefile2graph produces when given your Makefile. This doesn't necessarily include every image and file that the script outputs depending on how you structure your Makefile.

Do you think there is a problem with your image?

**Comment by agdal1125** [comment]
We don't have any problem with the image. We were just curious about how specific the image has to be. Thank you!
